### ISSUE TITLE
hotkeys.trigger('ctrl+f5') is not working

### ISSUE THREAD

**Issue by vsctest1** [Droogans/protractor-hotkeys#10]
i was trying to use Hotkeys however the above mentioned commands doesnt seems to work.
I tried hotkeys.trigger('ctrl+a') and it was working.
using the hotkeys.trigger('ctrl+f5') but it doesn't worked

please have a look?

**Comment by Droogans** [comment]
I never intended for this application to support refreshing the page in such a way. It's not portable between operating systems, and has a perfectly good way to accomplish this in protractor already.

http://www.protractortest.org/#/api?view=ProtractorBrowser.prototype.refresh

That should do what you want in a much more portable, consistent manner than relying on hotkey combinations.
