### ISSUE TITLE
Cant get copy and paste to work

### ISSUE THREAD

**Issue by gd46** [Droogans/protractor-hotkeys#8]
Can you give an example of a universal solution for copy paste? I am working on a MAC, but our tests are deployed to Windows machines so I'd like to have it work on both. I tried several combinations and I was only able to get basic keys to work. An example would be much appreciated, thank you.

**Comment by Droogans** [comment]
Just shooting from the hip here, but I wonder if you could add a hotkey that would work something like this:

``` js
let hotkeys = require('protractor-hotkeys');
hotkeys.HOTKEYS.modifier = process.platform === 'darwin' ? hotkeys.HOTKEYS.cmd : hotkeys.HOTKEYS.ctrl;

hotkeys.trigger('modifier+c');
hotkeys.trigger('modifier+v', { targetElement: $('#my-input-thing') });
```

Not sure how you'd highlight text, possibly with the `browser.actions()` helpers. Don't forget to set your `targetElement` to whatever you're trying to paste into.
