### ISSUE TITLE
hotkeys.trigger('ctrl+down') and   hotkeys.trigger('end') is not working

### ISSUE THREAD

**Issue by anuvratashu** [Droogans/protractor-hotkeys#9]
i was trying to use Hotkeys however the above mentioned commands doesnt seems to work.
I tried hotkeys.trigger('ctrl+a')  and it was working.

Scenario was that i want to move to end of scrollbar using the  hotkeys.trigger('end') but it doesn't worked

please have a look?

**Comment by Droogans** [comment]
I don't think keyboard events work like that in selenium.

Try using something like this instead.

```js
scrollToEnd() {
    browser.execute('document.getElementsByClassName("submit")[0].scrollIntoView();');
}
```

Where the `"submit"` element, a la `$('.submit')`, is some element that is located at the end of the page where the scroll bar runs out.
